AWSTemplateFormatVersion: 2010-09-09
Description: testing all the code here

Resources:
  AppStackAdminRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - 
         PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

Outputs:
  IAMRole:
    Description: IAM ROLE
    Value: !Ref  AppStackAdminRole

